### ISSUE TITLE
the constructor in the table breaks the game

### ISSUE THREAD

**Issue by LyubitelPokushat** [Ferlern/extended-UI-v7#20]
the constructor icon in the table breaks the game
crash report:
Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4024mb
Cores: 16
Mods: extended-ui:0.78

rhino.EvaluatorException: The choice of Java method arc.scene.ui.layout.Table.button matching JavaScript argument types (function,mindustry.ui.Styles$16,function) is ambiguous; candidate methods are: 
    class arc.scene.ui.layout.Cell button(arc.scene.style.Drawable,arc.scene.ui.ImageButton$ImageButtonStyle,java.lang.Runnable)
    class arc.scene.ui.layout.Cell button(arc.func.Cons,arc.scene.ui.Button$ButtonStyle,java.lang.Runnable) (schematics-table-ui#210)
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:756)
	at rhino.Context.reportRuntimeError(Context.java:802)
	at rhino.Context.reportRuntimeError4(Context.java:791)
	at rhino.NativeJavaMethod.findFunction(NativeJavaMethod.java:436)
	at rhino.NativeJavaMethod.findCachedFunction(NativeJavaMethod.java:238)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:120)
	at rhino.optimizer.OptRuntime.callN(OptRuntime.java:41)
	at rhino.gen.schematics_table_ui_22._c_buildTable_20(schematics-table-ui:210)
	at rhino.gen.schematics_table_ui_22.call(schematics-table-ui)
	at rhino.optimizer.OptRuntime.callName0(OptRuntime.java:61)
	at rhino.gen.schematics_table_ui_22._c_rebuildTable_19(schematics-table-ui:166)
	at rhino.gen.schematics_table_ui_22._c_anonymous_6(schematics-table-ui:65)
	at rhino.gen.schematics_table_ui_22.call(schematics-table-ui)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.schematics_table_ui_22.call(schematics-table-ui)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy1.run(Unknown Source)
	at arc.Events.lambda$run$2(Events.java:20)
	at arc.Events.fire(Events.java:36)
	at mindustry.core.Logic.update(Logic.java:406)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by Ferlern** [comment]
Finally I was able to track it down.

Thaks for the actual sprite name, it's fixed now.
